Pr to merge feature branch into development
talhawaqar/Weather-App pull request #2
Opened 2021-01-15 12:27 UTC by talhawaqar

This pr include the complete weather app. This weather app uses OpenWeatherMap API to display weather data to user.
There are the following aims of building this project.

-  How to use API using simple plain js
- Learn about async and await functions

2021-01-15 15:59 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @talhawaqar :hand: 
Great job on this app so far :+1: 
But we need to make some changes before moving on.

- [x] Your .eslintrc file is different from the one provided by Microverse. We need to use this configuration [instead](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json).

- [x] I liked your idea to show the flag's country from the inputted location. However, since this is a weather app, we still need to change something in the UI related to the current weather. As the requirement said, you can change the color of the background, to a color that reflects the current weather, or you can add a corresponding icon.
![Screenshot from 2021-01-15 13-09-23](https://user-images.githubusercontent.com/30977845/104750473-eb253e80-5732-11eb-9273-d52892f20e65.png)

Feel free to message me on Slack if you have questions.
Happy coding :computer: 
**Sergio Torres**

2021-01-20 11:42 UTC, whiz25 requested changes
## Changes Required :pray:
Nice work on the requested changes. The background image is fixed and `.eslintrc.json` is updated as requested, however, you have a comment in `dom.js` file. Please remove it as it makes your code ugly.

### Martin Afani

2021-01-20 11:42 UTC, whiz25 commented on src/dom.js
> +  // console.log(weather.weather[0]);
- remove this comment and any other comments in the codebase.

2021-01-20 11:58 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

Great job @talhawaqar :clap: :clap: :clap:, and thanks for making the required changes :hammer: by the previous TSE's

Now you can merge :green_circle: your project is approved :checkered_flag: 

## OPTIONAL:

- [ ] Now your project is approved, but please I have one request, add a live demo link in the readme.

## Happy Coding :tophat:

2021-01-29 13:55 UTC, merged